### ISSUE TITLE
500 error on invalid token

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/mithril.api#30]
Request:
`curl -H "Authorization: Bearer T25xNnNzOU8zaWVETVRzbVZrR0Uvdz08" "http://104.199.16.248:80/api/legal_entities" | jq`

Error:
`{
  "meta": {
    "url": "http://104.199.16.248/api/legal_entities",
    "type": "object",
    "request_id": null,
    "code": 500
  },
  "error": {
    "type": "internal_error"
  }
}`

**Comment by AlekzandrV** [comment]
The same error

**Comment by AlekzandrV** [comment]
@gmile the same error but on valid token

**Comment by gmile** [comment]
Should be good now
